### ISSUE TITLE
Kuma doesn't load

### ISSUE THREAD

**Issue by hashtagwilliam** [Raffaelbdl/kuma-browser#10]
Fresh Anki install. Doesn't load even with other addons disabled. Python 3.12 install on computer as well if that matters.

````
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19044

Traceback (most recent call last):
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\kuma\addon.py", line 79, in open_interface
    KumaAnki.window.KumaBrowser_Main = KumaBrowser_Main()
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\kuma\addon.py", line 30, in __init__
    Anki_SearchWidget(self),
  File "C:\Users\William\AppData\Roaming\Anki2\addons21\kuma\widget.py", line 53, in __init__
    self.current_deck = self.decks_list[0]
IndexError: list index out of range

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['kuma', 0, 'None', '']
AnkiMorphs ['472573498', 2024-05-18T12:57, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-07-09T07:54, 'None', '']
JPDB Anki Importer ['541896873', 2023-03-01T22:01, 'None', '']
PassFail 2 Remove the Easy and Hard buttons ['876946123', 2024-06-03T20:56, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T20:43, 'None', '']
True Retention by Card Maturity Simplified ['1779060522', 2020-06-28T08:45, 'None', '']
ankimorphs-japanese-mecab ['1974309724', 2024-03-21T06:40, 'None', '']

===IDs of active AnkiWeb add-ons===
1771074083 1779060522 1974309724 472573498 541896873 759844606 876946123

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```

**Comment by Raffaelbdl** [comment]
Thank you for testing the addon !

The issue seems to come from the fresh installation, since the addon is trying to access a deck which does not exist.

I will work on a fix to avoid the addon from crashing, in the meantime can you try to install the module after having created a deck ? 

Thank you very much

**Comment by hashtagwilliam** [comment]
Works for the most part. Thanks.
Only generated 4921/5000 from a top 5k deck, but that is another issue.
