### ISSUE TITLE
anki sends an error when trying to search vocab list on jpdb

### ISSUE THREAD

**Issue by milkshiiru** [Raffaelbdl/kuma-browser#11]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "urllib3.connectionpool", line 789, in urlopen
  File "urllib3.connectionpool", line 490, in _make_request
  File "urllib3.connectionpool", line 466, in _make_request
  File "urllib3.connectionpool", line 1095, in _validate_conn
  File "urllib3.connection", line 652, in connect
  File "urllib3.connection", line 805, in _ssl_wrap_socket_and_match_hostname
  File "urllib3.util.ssl_", line 465, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 509, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1074, in _create
  File "ssl", line 1343, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests.adapters", line 589, in send
  File "urllib3.connectionpool", line 843, in urlopen
  File "urllib3.util.retry", line 474, in increment
  File "urllib3.util.util", line 38, in reraise
  File "urllib3.connectionpool", line 789, in urlopen
  File "urllib3.connectionpool", line 490, in _make_request
  File "urllib3.connectionpool", line 466, in _make_request
  File "urllib3.connectionpool", line 1095, in _validate_conn
  File "urllib3.connection", line 652, in connect
  File "urllib3.connection", line 805, in _ssl_wrap_socket_and_match_hostname
  File "urllib3.util.ssl_", line 465, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 509, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1074, in _create
  File "ssl", line 1343, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\milkshiiru\AppData\Roaming\Anki2\addons21\kuma\jpdb_api.py", line 320, in generate_or_update
    notes = api.vocabulary_list(int(deck_id))
  File "C:\Users\milkshiiru\AppData\Roaming\Anki2\addons21\kuma\jpdb_api.py", line 39, in vocabulary_list
    response = requests.post(url, json=payload, headers=headers)
  File "requests.api", line 115, in post
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 604, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['kuma', 0, 'None', '']

===IDs of active AnkiWeb add-ons===

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-07-26T07:55, 'None', '']

**Comment by Raffaelbdl** [comment]
Thank you for trying the addon !

Unfortunately, I cannot find much information about the issue you are facing.
This [issue](https://stackoverflow.com/questions/75217175/python-request-aborted-connectionreseterror10054-an-existing-connection-was) suggests that proxies are the culprit, this [one](https://github.com/Azure/azure-cli/issues/28139) was solved by reinstalling the system :laughing:, and this [one](https://stackoverflow.com/questions/8814802/python-errno-10054-an-existing-connection-was-forcibly-closed-by-the-remote-h) solved it by requesting the server multiple times.

Do you have a VPN on hand to see if it works ? 
And if running the same command multiple times (even without VPN) solves it I could add a loop that tries to connect again periodically.

**Comment by Raffaelbdl** [comment]
Marking this as closed
