### ISSUE TITLE
Error trying to get a vocabList

### ISSUE THREAD

**Issue by PauloDaniel1993** [Raffaelbdl/kuma-browser#8]
I had the same problem with the JPDB Anki Note Creator, so, there is a big chance that there is something wrong with my system.

Python version: 3.11.6

```
Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "urllib3.connectionpool", line 467, in _make_request
  File "urllib3.connectionpool", line 1099, in _validate_conn
  File "urllib3.connection", line 653, in connect
  File "urllib3.connection", line 806, in _ssl_wrap_socket_and_match_hostname
  File "urllib3.util.ssl_", line 465, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 509, in _ssl_wrap_socket_impl
  File "ssl", line 501, in wrap_socket
  File "ssl", line 1074, in _create
  File "ssl", line 1343, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 793, in urlopen
  File "urllib3.connectionpool", line 491, in _make_request
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:1129)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 486, in send
  File "urllib3.connectionpool", line 847, in urlopen
  File "urllib3.util.retry", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jpdb.io', port=443): Max retries exceeded with url: /textbook/9/minna-no-nihongo-i/vocabulary-list (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pdc18\AppData\Roaming\Anki2\addons21\kuma\widget.py", line 232, in run
    entries = self.get_all_entries_from_vocab_list(self.url)
  File "C:\Users\pdc18\AppData\Roaming\Anki2\addons21\kuma\widget.py", line 241, in get_all_entries_from_vocab_list
    jpdb_soup = load_url(vl_url)
  File "C:\Users\pdc18\AppData\Roaming\Anki2\addons21\kuma\jpdb.py", line 22, in load_url
    return BeautifulSoup(requests.get(url).content, "html.parser")
  File "requests.api", line 73, in get
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='jpdb.io', port=443): Max retries exceeded with url: /textbook/9/minna-no-nihongo-i/vocabulary-list (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
'' ['kuma', 0, 'None', '']
Beautify-Anki 20 mizmu ['1116770498', 2023-10-31T18:51, 'None', mod]
Japanese Pitch Accent ['148002038', 2023-05-07T14:01, 'None', '']
Kanji Colorizer stroke order diagrams ['1964372878', 2024-01-08T17:48, 'None', mod]
Quick Colour Changing ['2491935955', 2023-10-19T04:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T02:43, 'None', '']
Straight Reward ['957961234', 2023-11-01T14:11, 'None', '']

===IDs of active AnkiWeb add-ons===
1116770498 148002038 1771074083 1964372878 2491935955 957961234

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

```

Error from the command runned direct from terminal
```
Creating new list minna-no-nihongo-i_vocabulary-list
Traceback (most recent call last):
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jpdb.io', port=443): Max retries exceeded with url: /textbook/9/minna-no-nihongo-i/vocabulary-list (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\__main__.py", line 75, in <module>
    app.run(main)
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\__main__.py", line 58, in main
    vocab_entries = db.get_list(FLAGS.vocablist)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\database.py", line 117, in get_list
    vocab = get_all_vocab_entries(url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\scraping.py", line 23, in get_all_vocab_entries
    jpdb = load_url(root_url)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\scraping.py", line 8, in load_url
    return BeautifulSoup(requests.get(url).content, "html.parser")
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='jpdb.io', port=443): Max retries exceeded with url: /textbook/9/minna-no-nihongo-i/vocabulary-list (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
```

I tried in linux too, had the same error... Is there any idea about what could be causing this problem?

**Comment by Raffaelbdl** [comment]
Hi! Thank you for testing this addon
Concerning your issue, it might be related to the security protocol.

Can you replace the definition of `load_url` in the file `jpdb.py` and let me know if it works ?
```python
def load_url(url: Url) -> BeautifulSoup:
    return BeautifulSoup(requests.get(url, verify=False).content, "html.parser")
```  

If that does the trick I will add an option to deactivate the security (and remove the warnings in the console)

**Comment by PauloDaniel1993** [comment]
The same error.

Strange that the first time I did run after the fix, it continued to run until 2%, then gave me another error, but after that, same connection pool error.

I put in the standalone script too, to see if something appeared there, and same thing.(I observed that the type for the url parameter is str instead of Url there, so no problem with this))

**Comment by Raffaelbdl** [comment]
It seems that the issue comes either from the inner requests package, or maybe from jpdb itself.

One issue I had with jpdb is that they seem to restrict access when there are too many requests, that is why I could not make the creation of decks faster. Maybe you could try again with a different network? 

I have joined to this comment the result of the first step of the deck creation. You can drop this json in `addons21/kuma/vocab_lists/` folder after removing the `.json` at the end of the name, then retry creating a new vocabulary list.
It should skip the search of new cards and directly start creating them. 

[minna-no-nihongo-i.json](https://github.com/Raffaelbdl/kuma-browser/files/15126497/minna-no-nihongo-i.json)

If it is a server issue, you may be able to create the deck bit by bit since the second part skips cards that already exist in the database.

Also, can you check if it happens when searching for a word in the `JPDB` tab, like 熊 for instance :smile:

**Comment by PauloDaniel1993** [comment]
now I was able to replicate the problem I said before
```
**Generating Package.:   0%|                                                                     | 0/979 [00:00<?, ?it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   2%|█                                                           | 18/979 [00:00<00:17, 55.24it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   2%|█▍                                                          | 24/979 [00:01<01:11, 13.34it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   3%|█▋                                                          | 27/979 [00:02<01:33, 10.19it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   3%|█▊                                                          | 29/979 [00:02<01:46,  8.94it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   3%|█▉                                                          | 31/979 [00:02<02:00,  7.88it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   3%|█▉                                                          | 32/979 [00:03<02:07,  7.45it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   3%|██                                                          | 33/979 [00:03<02:16,  6.95it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   3%|██                                                          | 34/979 [00:03<02:27,  6.42it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▏                                                         | 35/979 [00:03<02:33,  6.14it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▏                                                         | 36/979 [00:03<02:37,  5.98it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▎                                                         | 37/979 [00:04<02:42,  5.79it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▎                                                         | 38/979 [00:04<02:50,  5.51it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▍                                                         | 39/979 [00:04<02:56,  5.33it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▍                                                         | 40/979 [00:04<02:59,  5.24it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▌                                                         | 41/979 [00:04<03:02,  5.13it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▌                                                         | 42/979 [00:05<03:06,  5.04it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▋                                                         | 43/979 [00:05<03:03,  5.09it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   4%|██▋                                                         | 44/979 [00:05<03:02,  5.11it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|██▊                                                         | 45/979 [00:05<03:01,  5.14it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|██▊                                                         | 46/979 [00:05<03:06,  5.00it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|██▉                                                         | 47/979 [00:06<02:59,  5.19it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|██▉                                                         | 48/979 [00:06<02:55,  5.30it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|███                                                         | 49/979 [00:06<02:53,  5.36it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|███                                                         | 50/979 [00:06<02:55,  5.28it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|███▏                                                        | 51/979 [00:06<02:55,  5.28it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|███▏                                                        | 52/979 [00:06<02:57,  5.24it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   5%|███▏                                                        | 53/979 [00:07<03:04,  5.03it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   6%|███▎                                                        | 54/979 [00:07<03:04,  5.03it/s]C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jpdb.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Generating Package.:   6%|███▎                                                        | 54/979 [00:07<02:09,  7.13it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\__main__.py", line 75, in <module>
    app.run(main)
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\pdc18\AppData\Local\Programs\Python\Python312\Lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\__main__.py", line 59, in main
    db.write_apkg_from_list("output.apkg", vocab_entries)
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\database.py", line 143, in write_apkg_from_list
    deck.add_note(AnkiNote.from_note(self.get_note(e), model=self.model))
                                     ^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\database.py", line 101, in get_note
    note_ = note.Note.from_jpdb(url, pitch_dictionary=self.pitch_dictionary)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdc18\Downloads\app\jpdb-anki\jpdb_anki\fields\note.py", line 21, in from_jpdb
    note.expression = jpdb.find("title").text.split(" ")[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'
``` 
Then, if I try again, it gives me a connection pool error


---------
Seems like you are right. It works throught VPN... But Very slowly. Like, one request per second. Would it be a case to add a optional throttle?

---------
yep, seems like my ip is banned from jpdb

----------
Okay, I can access again. And seems like there is a API now that returns the data needed.
https://jpdb.stoplight.io/

**Comment by Raffaelbdl** [comment]
If it works with a VPN it's a good news ^^
Like I mentioned, I cannot collect data faster than 1 note per second due to the JPDB limitations on web scraping.

On the other hand, I just opened a Pull Request that includes a new tab to make cards using the API you mentioned. Thanks for letting me know it existed! I will keep working on it in the next days (and clean up the rest of the code on the way).

If you clone from the branch `api` then replace the addon files with the ones inside the `kuma/` directory you should be able to use it.
The Token is the one at the very bottom of the settings page in your JPDB account.
The Deck Id is the one from your own decks, which you can obtain in JPDB from the `Learn(x)` like in the pictures.

![image](https://github.com/Raffaelbdl/kuma-browser/assets/67725350/7f268ab0-dcd4-4298-96de-d52816608e4f)
![image](https://github.com/Raffaelbdl/kuma-browser/assets/67725350/3f57dd11-e2d1-409c-a8db-86aae4a0975a)
![image](https://github.com/Raffaelbdl/kuma-browser/assets/67725350/90da18af-5680-4ea7-bfa8-e9bc245a26e1)
![image](https://github.com/Raffaelbdl/kuma-browser/assets/67725350/463e27c4-bac8-40e9-9d21-ba25165058ab)

But the API is quite limited:
- (1) cannot search arbitrary words
- (2) does not provide example sentences
- (3) I manually added part of speech elements (Noun, Verb etc..), and I print the ones I have not seen. Please come back if you find ones that are not implemented :hugs:  
- (4) you need to add the vocabulary list to you own decks before being able to generate cards

I hope it can still help to create decks without getting banned from JPDB :laughing:

**Comment by PauloDaniel1993** [comment]
Awesome!
Yes, your solution is currently better. Sad that with vpn it takes something like 5 seconds per card TT_TT

Thanks for the help
